import sys
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMainWindow, QApplication, QPushButton, QWidget, QAction, QGridLayout, QTabWidget, QVBoxLayout
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot
from hodomon import hodomon


class App(QMainWindow):

    def __init__(self):
        super().__init__()
        self.title = 'HodoMon'
        self.left = 0
        self.top = 0
        self.width = 900
        self.height = 100
        self.setWindowTitle(self.title)
        self.setGeometry(self.left, self.top, self.width, self.height)

        self.table_widget = MyTableWidget(self)
        self.setCentralWidget(self.table_widget)

        self.show()


class MyTableWidget(QWidget):

    def __init__(self, parent):
        super(QWidget, self).__init__(parent)
        self.layout = QVBoxLayout(self)

        # Initialize tab screen
        self.tabs = QTabWidget()
        # Display voltage
        self.tab0 = QWidget()
        # H1 hodoscope
        self.tabs1 = QTabWidget()
        self.tab1 = QWidget()
        self.tab2 = QWidget()
        self.tab3 = QWidget()
        self.tab4 = QWidget()
        # H1 hodoscope
        self.tabs2 = QTabWidget()
        self.tab5 = QWidget()
        self.tab6 = QWidget()
        self.tab7 = QWidget()
        self.tab8 = QWidget()
        # H3 hodoscope
        self.tabs3 = QTabWidget()
        self.tab9 = QWidget()
        self.tab10 = QWidget()
        # H4 hodoscope
        self.tabs4 = QTabWidget()
        self.tab11 = QWidget()
        self.tab12 = QWidget()
        self.tab13 = QWidget()
        self.tab14 = QWidget()
        self.tab15 = QWidget()
        self.tab16 = QWidget()
        self.tab17 = QWidget()
        self.tab18 = QWidget()
        self.tab19 = QWidget()
        self.tab20 = QWidget()
        self.tab21 = QWidget()
        self.tab22 = QWidget()
        # Expert Button
        self.tab23 = QWidget()
        self.tabs.resize(300, 200)

        # Add tabs
        self.tabs.addTab(self.tab0, "Voltage")
        ######
        self.tabs1.addTab(self.tab1, "H1XB")
        self.tabs1.addTab(self.tab2, "H1XT")
        self.tabs1.addTab(self.tab3, "H1YL")
        self.tabs1.addTab(self.tab4, "H1YR")
        self.tabs.addTab(self.tabs1, "H1")
        ######
        self.tabs2.addTab(self.tab5, "H2XT")
        self.tabs2.addTab(self.tab6, "H2XB")
        self.tabs2.addTab(self.tab7, "H2YR")
        self.tabs2.addTab(self.tab8, "H2YL")
        self.tabs.addTab(self.tabs2, "H2")
        ######
        self.tabs3.addTab(self.tab9, "H3XB")
        self.tabs3.addTab(self.tab10, "H3XT")
        self.tabs.addTab(self.tabs3, "H3")
        ######
        self.tabs4.addTab(self.tab11, "H4Y1L-l")
        self.tabs4.addTab(self.tab12, "H4Y1L-r")
        self.tabs4.addTab(self.tab13, "H4Y1R-l")
        self.tabs4.addTab(self.tab14, "H4Y1R-r")
        self.tabs4.addTab(self.tab15, "H4Y2L-l")
        self.tabs4.addTab(self.tab16, "H4Y2L-r")
        self.tabs4.addTab(self.tab17, "H4Y2R-l")
        self.tabs4.addTab(self.tab18, "H4Y2R-r")
        self.tabs4.addTab(self.tab19, "H4XB-d")
        self.tabs4.addTab(self.tab20, "H4XB-u")
        self.tabs4.addTab(self.tab21, "H4XT-d")
        self.tabs4.addTab(self.tab22, "H4XT-u")
        self.tabs.addTab(self.tabs4, "H4")
        #
        self.tabs.addTab(self.tab23, "EXPERT")

        # Create expert tab
        self.tab23.layout = QGridLayout(self)
        self.pushButton_23_0 = QPushButton("ON")
        self.pushButton_23_1 = QPushButton("OFF")
        self.pushButton_23_2 = QPushButton("SET-NOMINAL")
        self.pushButton_23_3 = QPushButton("SET-CHANNEL")
        self.pushButton_23_4 = QPushButton("SET-PLATEAU")
        #
        self.tab23.layout.addWidget(self.pushButton_23_0, 0, 0)
        self.tab23.layout.addWidget(self.pushButton_23_1, 0, 1)
        self.tab23.layout.addWidget(self.pushButton_23_2, 0, 2)
        self.tab23.layout.addWidget(self.pushButton_23_3, 1, 0)
        self.tab23.layout.addWidget(self.pushButton_23_4, 1, 1)
        #
        self.tab23.setLayout(self.tab23.layout)

        # Create H1XB PMTs
        self.tab1.layout = QGridLayout(self)
        self.pushButton_1_1 = QPushButton(" Hits ")
        self.pushButton_1_2 = QPushButton(" Efficiency ")
        self.pushButton_1_3 = QPushButton(" 1 ")
        self.pushButton_1_3.clicked.connect(lambda: self.action("H1XB_1_MV"))
        self.pushButton_1_4 = QPushButton(" 2 ")
        self.pushButton_1_4.clicked.connect(lambda: self.action("H1XB_2_MV"))
        self.pushButton_1_5 = QPushButton(" 3 ")
        self.pushButton_1_5.clicked.connect(lambda: self.action("H1XB_3_MV"))
        self.pushButton_1_6 = QPushButton(" 4 ")
        self.pushButton_1_6.clicked.connect(lambda: self.action("H1XB_4_MV"))
        self.pushButton_1_7 = QPushButton(" 5 ")
        self.pushButton_1_7.clicked.connect(lambda: self.action("H1XB_5_MV"))
        self.pushButton_1_8 = QPushButton(" 6 ")
        self.pushButton_1_8.clicked.connect(lambda: self.action("H1XB_6_MV"))
        self.pushButton_1_9 = QPushButton(" 7 ")
        self.pushButton_1_9.clicked.connect(lambda: self.action("H1XB_7_MV"))
        self.pushButton_1_10 = QPushButton(" 8 ")
        self.pushButton_1_10.clicked.connect(lambda: self.action("H1XB_8_MV"))
        self.pushButton_1_11 = QPushButton(" 9 ")
        self.pushButton_1_11.clicked.connect(lambda: self.action("H1XB_9_MV"))
        self.pushButton_1_12 = QPushButton(" 10 ")
        self.pushButton_1_12.clicked.connect(lambda: self.action("H1XB_10_MV"))
        self.pushButton_1_13 = QPushButton(" 11 ")
        self.pushButton_1_13.clicked.connect(lambda: self.action("H1XB_11_MV"))
        self.pushButton_1_14 = QPushButton(" 12 ")
        self.pushButton_1_14.clicked.connect(lambda: self.action("H1XB_12_MV"))
        self.pushButton_1_15 = QPushButton(" 13 ")
        self.pushButton_1_15.clicked.connect(lambda: self.action("H1XB_13_MV"))
        self.pushButton_1_16 = QPushButton(" 14 ")
        self.pushButton_1_16.clicked.connect(lambda: self.action("H1XB_14_MV"))
        self.pushButton_1_17 = QPushButton(" 15 ")
        self.pushButton_1_17.clicked.connect(lambda: self.action("H1XB_15_MV"))
        self.pushButton_1_18 = QPushButton(" 16 ")
        self.pushButton_1_18.clicked.connect(lambda: self.action("H1XB_16_MV"))
        self.pushButton_1_19 = QPushButton(" 17 ")
        self.pushButton_1_19.clicked.connect(lambda: self.action("H1XB_17_MV"))
        self.pushButton_1_20 = QPushButton(" 18 ")
        self.pushButton_1_20.clicked.connect(lambda: self.action("H1XB_18_MV"))
        self.pushButton_1_21 = QPushButton(" 19 ")
        self.pushButton_1_21.clicked.connect(lambda: self.action("H1XB_19_MV"))
        self.pushButton_1_22 = QPushButton(" 20 ")
        self.pushButton_1_22.clicked.connect(lambda: self.action("H1XB_20_MV"))
        self.pushButton_1_23 = QPushButton(" 21 ")
        self.pushButton_1_23.clicked.connect(lambda: self.action("H1XB_21_MV"))
        self.pushButton_1_24 = QPushButton(" 22 ")
        self.pushButton_1_24.clicked.connect(lambda: self.action("H1XB_22_MV"))
        self.pushButton_1_25 = QPushButton(" 23 ")
        self.pushButton_1_25.clicked.connect(lambda: self.action("H1XB_23_MV"))
        #
        self.tab1.layout.addWidget(self.pushButton_1_1, 0, 0)
        self.tab1.layout.addWidget(self.pushButton_1_2, 0, 1)
        self.tab1.layout.addWidget(self.pushButton_1_3, 1, 0)
        self.tab1.layout.addWidget(self.pushButton_1_4, 1, 1)
        self.tab1.layout.addWidget(self.pushButton_1_5, 1, 2)
        self.tab1.layout.addWidget(self.pushButton_1_6, 1, 3)
        self.tab1.layout.addWidget(self.pushButton_1_7, 1, 4)
        self.tab1.layout.addWidget(self.pushButton_1_8, 2, 0)
        self.tab1.layout.addWidget(self.pushButton_1_9, 2, 1)
        self.tab1.layout.addWidget(self.pushButton_1_10, 2, 2)
        self.tab1.layout.addWidget(self.pushButton_1_11, 2, 3)
        self.tab1.layout.addWidget(self.pushButton_1_12, 2, 4)
        self.tab1.layout.addWidget(self.pushButton_1_13, 3, 0)
        self.tab1.layout.addWidget(self.pushButton_1_14, 3, 1)
        self.tab1.layout.addWidget(self.pushButton_1_15, 3, 2)
        self.tab1.layout.addWidget(self.pushButton_1_16, 3, 3)
        self.tab1.layout.addWidget(self.pushButton_1_17, 3, 4)
        self.tab1.layout.addWidget(self.pushButton_1_18, 4, 0)
        self.tab1.layout.addWidget(self.pushButton_1_19, 4, 1)
        self.tab1.layout.addWidget(self.pushButton_1_20, 4, 2)
        self.tab1.layout.addWidget(self.pushButton_1_21, 4, 3)
        self.tab1.layout.addWidget(self.pushButton_1_22, 4, 4)
        self.tab1.layout.addWidget(self.pushButton_1_23, 5, 0)
        self.tab1.layout.addWidget(self.pushButton_1_24, 5, 1)
        self.tab1.layout.addWidget(self.pushButton_1_25, 5, 2)
        #
        self.tab1.setLayout(self.tab1.layout)

        # Create H1XT PMTs
        self.tab2.layout = QGridLayout(self)
        self.pushButton_2_1 = QPushButton(" Hits ")
        self.pushButton_2_2 = QPushButton(" Efficiency ")
        self.pushButton_2_3 = QPushButton(" 1 ")
        self.pushButton_2_4 = QPushButton(" 2 ")
        self.pushButton_2_5 = QPushButton(" 3 ")
        self.pushButton_2_6 = QPushButton(" 4 ")
        self.pushButton_2_7 = QPushButton(" 5 ")
        self.pushButton_2_8 = QPushButton(" 6 ")
        self.pushButton_2_9 = QPushButton(" 7 ")
        self.pushButton_2_10 = QPushButton(" 8 ")
        self.pushButton_2_11 = QPushButton(" 9 ")
        self.pushButton_2_12 = QPushButton(" 10 ")
        self.pushButton_2_13 = QPushButton(" 11 ")
        self.pushButton_2_14 = QPushButton(" 12 ")
        self.pushButton_2_15 = QPushButton(" 13 ")
        self.pushButton_2_16 = QPushButton(" 14 ")
        self.pushButton_2_17 = QPushButton(" 15 ")
        self.pushButton_2_18 = QPushButton(" 16 ")
        self.pushButton_2_19 = QPushButton(" 17 ")
        self.pushButton_2_20 = QPushButton(" 18 ")
        self.pushButton_2_21 = QPushButton(" 19 ")
        self.pushButton_2_22 = QPushButton(" 20 ")
        self.pushButton_2_23 = QPushButton(" 21 ")
        self.pushButton_2_24 = QPushButton(" 22 ")
        self.pushButton_2_25 = QPushButton(" 23 ")
        #
        self.tab2.layout.addWidget(self.pushButton_2_1, 0, 0)
        self.tab2.layout.addWidget(self.pushButton_2_2, 0, 1)
        self.tab2.layout.addWidget(self.pushButton_2_3, 1, 0)
        self.tab2.layout.addWidget(self.pushButton_2_4, 1, 1)
        self.tab2.layout.addWidget(self.pushButton_2_5, 1, 2)
        self.tab2.layout.addWidget(self.pushButton_2_6, 1, 3)
        self.tab2.layout.addWidget(self.pushButton_2_7, 1, 4)
        self.tab2.layout.addWidget(self.pushButton_2_8, 2, 0)
        self.tab2.layout.addWidget(self.pushButton_2_9, 2, 1)
        self.tab2.layout.addWidget(self.pushButton_2_10, 2, 2)
        self.tab2.layout.addWidget(self.pushButton_2_11, 2, 3)
        self.tab2.layout.addWidget(self.pushButton_2_12, 2, 4)
        self.tab2.layout.addWidget(self.pushButton_2_13, 3, 0)
        self.tab2.layout.addWidget(self.pushButton_2_14, 3, 1)
        self.tab2.layout.addWidget(self.pushButton_2_15, 3, 2)
        self.tab2.layout.addWidget(self.pushButton_2_16, 3, 3)
        self.tab2.layout.addWidget(self.pushButton_2_17, 3, 4)
        self.tab2.layout.addWidget(self.pushButton_2_18, 4, 0)
        self.tab2.layout.addWidget(self.pushButton_2_19, 4, 1)
        self.tab2.layout.addWidget(self.pushButton_2_20, 4, 2)
        self.tab2.layout.addWidget(self.pushButton_2_21, 4, 3)
        self.tab2.layout.addWidget(self.pushButton_2_22, 4, 4)
        self.tab2.layout.addWidget(self.pushButton_2_23, 5, 0)
        self.tab2.layout.addWidget(self.pushButton_2_24, 5, 1)
        self.tab2.layout.addWidget(self.pushButton_2_25, 5, 2)
        #
        self.tab2.setLayout(self.tab2.layout)

        # Create H1YL PMTs
        self.tab3.layout = QGridLayout(self)
        self.pushButton_3_1 = QPushButton(" Hits ")
        self.pushButton_3_2 = QPushButton(" Efficiency ")
        self.pushButton_3_3 = QPushButton(" 1 ")
        self.pushButton_3_4 = QPushButton(" 2 ")
        self.pushButton_3_5 = QPushButton(" 3 ")
        self.pushButton_3_6 = QPushButton(" 4 ")
        self.pushButton_3_7 = QPushButton(" 5 ")
        self.pushButton_3_8 = QPushButton(" 6 ")
        self.pushButton_3_9 = QPushButton(" 7 ")
        self.pushButton_3_10 = QPushButton(" 8 ")
        self.pushButton_3_11 = QPushButton(" 9 ")
        self.pushButton_3_12 = QPushButton(" 10 ")
        self.pushButton_3_13 = QPushButton(" 11 ")
        self.pushButton_3_14 = QPushButton(" 12 ")
        self.pushButton_3_15 = QPushButton(" 13 ")
        self.pushButton_3_16 = QPushButton(" 14 ")
        self.pushButton_3_17 = QPushButton(" 15 ")
        self.pushButton_3_18 = QPushButton(" 16 ")
        self.pushButton_3_19 = QPushButton(" 17 ")
        self.pushButton_3_20 = QPushButton(" 18 ")
        self.pushButton_3_21 = QPushButton(" 19 ")
        self.pushButton_3_22 = QPushButton(" 20 ")
        #
        self.tab3.layout.addWidget(self.pushButton_3_1, 0, 0)
        self.tab3.layout.addWidget(self.pushButton_3_2, 0, 1)
        self.tab3.layout.addWidget(self.pushButton_3_3, 1, 0)
        self.tab3.layout.addWidget(self.pushButton_3_4, 1, 1)
        self.tab3.layout.addWidget(self.pushButton_3_5, 1, 2)
        self.tab3.layout.addWidget(self.pushButton_3_6, 1, 3)
        self.tab3.layout.addWidget(self.pushButton_3_7, 1, 4)
        self.tab3.layout.addWidget(self.pushButton_3_8, 2, 0)
        self.tab3.layout.addWidget(self.pushButton_3_9, 2, 1)
        self.tab3.layout.addWidget(self.pushButton_3_10, 2, 2)
        self.tab3.layout.addWidget(self.pushButton_3_11, 2, 3)
        self.tab3.layout.addWidget(self.pushButton_3_12, 2, 4)
        self.tab3.layout.addWidget(self.pushButton_3_13, 3, 0)
        self.tab3.layout.addWidget(self.pushButton_3_14, 3, 1)
        self.tab3.layout.addWidget(self.pushButton_3_15, 3, 2)
        self.tab3.layout.addWidget(self.pushButton_3_16, 3, 3)
        self.tab3.layout.addWidget(self.pushButton_3_17, 3, 4)
        self.tab3.layout.addWidget(self.pushButton_3_18, 4, 0)
        self.tab3.layout.addWidget(self.pushButton_3_19, 4, 1)
        self.tab3.layout.addWidget(self.pushButton_3_20, 4, 2)
        self.tab3.layout.addWidget(self.pushButton_3_21, 4, 3)
        self.tab3.layout.addWidget(self.pushButton_3_22, 4, 4)
        #
        self.tab3.setLayout(self.tab3.layout)

        # Create H1YR PMTs
        self.tab4.layout = QGridLayout(self)
        self.pushButton_4_1 = QPushButton(" Hits ")
        self.pushButton_4_2 = QPushButton(" Efficiency ")
        self.pushButton_4_3 = QPushButton(" 1 ")
        self.pushButton_4_4 = QPushButton(" 2 ")
        self.pushButton_4_5 = QPushButton(" 3 ")
        self.pushButton_4_6 = QPushButton(" 4 ")
        self.pushButton_4_7 = QPushButton(" 5 ")
        self.pushButton_4_8 = QPushButton(" 6 ")
        self.pushButton_4_9 = QPushButton(" 7 ")
        self.pushButton_4_10 = QPushButton(" 8 ")
        self.pushButton_4_11 = QPushButton(" 9 ")
        self.pushButton_4_12 = QPushButton(" 10 ")
        self.pushButton_4_13 = QPushButton(" 11 ")
        self.pushButton_4_14 = QPushButton(" 12 ")
        self.pushButton_4_15 = QPushButton(" 13 ")
        self.pushButton_4_16 = QPushButton(" 14 ")
        self.pushButton_4_17 = QPushButton(" 15 ")
        self.pushButton_4_18 = QPushButton(" 16 ")
        self.pushButton_4_19 = QPushButton(" 17 ")
        self.pushButton_4_20 = QPushButton(" 18 ")
        self.pushButton_4_21 = QPushButton(" 19 ")
        self.pushButton_4_22 = QPushButton(" 20 ")
        #
        self.tab4.layout.addWidget(self.pushButton_4_1, 0, 0)
        self.tab4.layout.addWidget(self.pushButton_4_2, 0, 1)
        self.tab4.layout.addWidget(self.pushButton_4_3, 1, 0)
        self.tab4.layout.addWidget(self.pushButton_4_4, 1, 1)
        self.tab4.layout.addWidget(self.pushButton_4_5, 1, 2)
        self.tab4.layout.addWidget(self.pushButton_4_6, 1, 3)
        self.tab4.layout.addWidget(self.pushButton_4_7, 1, 4)
        self.tab4.layout.addWidget(self.pushButton_4_8, 2, 0)
        self.tab4.layout.addWidget(self.pushButton_4_9, 2, 1)
        self.tab4.layout.addWidget(self.pushButton_4_10, 2, 2)
        self.tab4.layout.addWidget(self.pushButton_4_11, 2, 3)
        self.tab4.layout.addWidget(self.pushButton_4_12, 2, 4)
        self.tab4.layout.addWidget(self.pushButton_4_13, 3, 0)
        self.tab4.layout.addWidget(self.pushButton_4_14, 3, 1)
        self.tab4.layout.addWidget(self.pushButton_4_15, 3, 2)
        self.tab4.layout.addWidget(self.pushButton_4_16, 3, 3)
        self.tab4.layout.addWidget(self.pushButton_4_17, 3, 4)
        self.tab4.layout.addWidget(self.pushButton_4_18, 4, 0)
        self.tab4.layout.addWidget(self.pushButton_4_19, 4, 1)
        self.tab4.layout.addWidget(self.pushButton_4_20, 4, 2)
        self.tab4.layout.addWidget(self.pushButton_4_21, 4, 3)
        self.tab4.layout.addWidget(self.pushButton_4_22, 4, 4)
        #
        self.tab4.setLayout(self.tab4.layout)


        # Add tabs to widget
        self.layout.addWidget(self.tabs)
        self.setLayout(self.layout)

    @pyqtSlot()
    def action(self, name):
        A = hodomon(name)
        A.display()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = App()
    sys.exit(app.exec_())